# Questions on NumPy Mathematics

* How to get element-wise true division of an array using Numpy?
* How to calculate the element-wise absolute value of NumPy array?
* Compute the negative of the NumPy array
* Multiply 2d numpy array corresponding to 1d array
* Computes the inner product of two arrays
* Compute the nth percentile of the NumPy array
* Calculate the n-th order discrete difference along the given axis
* Calculate the sum of all columns in a 2D NumPy array
* Calculate average values of two given NumPy arrays
* How to compute numerical negative value for all elements in a given NumPy array?
* How to get the floor, ceiling and truncated values of the elements of a numpy array?
* How to round elements of the NumPy array to the nearest integer?
* Find the round off the values of the given matrix
* Determine the positive square-root of an array
* Evaluate Einstein’s summation convention of two multidimensional NumPy arrays

# Questions on NumPy Sorting and Searching

[x] How to get the indices of the sorted array using NumPy in Python?
* Finding the k smallest values of a NumPy array
* How to get the n-largest values of an array using NumPy?
[x] Sort the values in a matrix
[x] Filter out integers from float numpy array
* Find the indices into a sorted array

In [68]:
# How to get the indices of the sorted array using NumPy in Python?
import numpy as np

rng = np.random
random_array = rng.randint(0,5,5)
sorted_index = np.argsort(random_array)
print(random_array)
print(sorted_index)

[4 4 4 0 1]
[3 4 0 1 2]


In [112]:
# Finding the k smallest values of a NumPy array

import numpy as np

rng = np.random
random_array = rng.randint(0,5,5)
k = 3
smallest_values = np.sort(random_array)[k]
print(random_array)
print(smallest_values)



[1 2 4 3 1]
3


In [ ]:
# How to get the n-largest values of an array using NumPy?

In [66]:
# Sort the values in a matrix


import numpy as np

rng = np.random
random_array = rng.randint(0,5,size=(3,3))
print(random_array)

np.sort(random_array)

[[3 4 0]
 [3 3 3]
 [3 0 0]]


array([[0, 3, 4],
       [3, 3, 3],
       [0, 0, 3]])

In [80]:
#Filter out integers from float numpy array

import numpy as np

rng = np.random
random_array = np.array([ 0.33589674,-1.56514918,-0.48906022,1.23497836, 0.09571005])
print(random_array)

filtered_array = np.modf(random_array)
print(filtered_array[1])


[ 0.33589674 -1.56514918 -0.48906022  1.23497836  0.09571005]
[ 0. -1. -0.  1.  0.]


# Questions on NumPy Random

[x] Create a Numpy array with random values
[x] How to choose elements from the list with different probability using NumPy?
[x] How to get weighted random choice in Python?
[x] Generate Random Numbers From The Uniform Distribution using NumPy
[x] Get Random Elements form geometric distribution
[x] Get Random elements from Laplace distribution
[x] Return a Matrix of random values from a uniform distribution
[x] Return a Matrix of random values from a Gaussian distribution

In [31]:
# Create a Numpy array with random values

import numpy as np

rng = np.random
random_array = rng.randint(0,5,5)
print(type(random_array))
print(random_array)


<class 'numpy.ndarray'>
[3 1 1 0 2]


In [58]:
# How to choose elements from the list with different probability using NumPy?

import numpy as np

rng = np.random
random_array = rng.randint(0,5,5)
w = [0.3,0.2,0.2,0.2,0.1]

print(random_array)
print(w)
print(rng.choice(random_array,p=w))


[3 0 0 4 1]
[0.3, 0.2, 0.2, 0.2, 0.1]
1


In [52]:
# How to get weighted random choice in Python?

import random 
import numpy as np

rng = np.random
random_array = rng.randint(0,5,5)
w = [x for x in range(1,6)]

print(random_array)
print(w)

random_choice = random.choices(random_array,w,k=1)
print(random_choice)

[3 2 0 4 1]
[1, 2, 3, 4, 5]
[1]


In [21]:
# Generate Random Numbers From The Uniform Distribution using NumPy

import numpy as np

rng = np.random
value_from_uniform = rng.uniform()
print(value_from_uniform)

0.2525736458609297


In [23]:
#Get Random Elements form geometric distribution

import numpy as np

rng = np.random

value_from_geometric = rng.geometric(0.35)
print(value_from_geometric)

7


In [24]:
#Get Random elements from Laplace distribution

import numpy as np

rng = np.random
value_from_laplace = rng.laplace()
print(value_from_laplace)

1.6625502737058733


In [19]:
# Return a Matrix of random values from a uniform distribution

import numpy as np

rng = np.random
random_uniform_array = rng.uniform(0,5,(3,3))
print(random_uniform_array)

[[1.76193327 1.57506645 1.36090448]
 [1.9389375  0.73962324 2.18846955]
 [3.35589716 0.38240967 4.16169106]]


# Questions on NumPy Linear Algebra

* Find a matrix or vector norm using NumPy
* Calculate the QR decomposition of a given matrix using NumPy
* Compute the condition number of a given matrix using NumPy
* Compute the eigenvalues and right eigenvectors of a given square array using NumPy?
* Calculate the Euclidean distance using NumPy

In [116]:
# Find a matrix or vector norm using NumPy

import numpy as np
from numpy import linalg as LA

rng = np.random
random_array = rng.randint(0,5,(3,3))
print(random_array)

norm = LA.norm(random_array)
print(norm)




[[0 4 0]
 [0 3 1]
 [1 1 1]]
5.385164807134504


In [118]:
# Calculate the QR decomposition of a given matrix using NumPy



In [119]:
# Compute the condition number of a given matrix using NumPy

import numpy as np
from numpy import linalg as LA

rng = np.random
random_array = rng.randint(0,5,(3,3))
print(random_array)

cond = LA.cond(random_array)
print(cond)

[[3 3 3]
 [3 0 1]
 [3 4 1]]
5.312868341867965


In [120]:
# Compute the eigenvalues and right eigenvectors of a given square array using NumPy?
import numpy as np
from numpy import linalg as LA

rng = np.random
random_array = rng.randint(0,5,(3,3))
print(random_array)
eigvalues = LA.eig(random_array)
print(eigvalues)

[[1 2 0]
 [1 1 3]
 [1 2 3]]
(array([ 5.0806044 ,  0.72918152, -0.80978592]), array([[-0.29980387, -0.94430137,  0.73244635],
       [-0.61169049,  0.12786713, -0.66278554],
       [-0.73208768,  0.3032242 ,  0.15568453]]))


In [124]:
# Calculate the Euclidean distance using NumPy

import numpy as np
from numpy import linalg as LA

rng = np.random
random_array1 = rng.randint(0,5,3)
random_array2 = rng.randint(0,5,3)
print(random_array1)
print(random_array2)

euclidean = LA.norm(random_array1-random_array2)
print(euclidean)


[3 4 1]
[0 4 0]
3.1622776601683795


# Questions on NumPy Indexing

* Replace NumPy array elements that doesn’t satisfy the given condition
* Return the indices of elements where the given condition is satisfied
* Replace NaN values with average of columns
* Replace negative value with zero in numpy array
* How to get values of an NumPy array at certain index positions?
* Find indices of elements equal to zero in a NumPy array
* How to Remove columns in Numpy array that contains non-numeric values?
* How to access different rows of a multidimensional NumPy array?
* Get row numbers of NumPy array having element larger than X
* Get filled the diagonals of NumPy array
* Check elements present in the NumPy array
* Combined array index by index